In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt 

In [2]:
A = np.array([[1, 1, 0], [1, 2, 2], [0, 2, -1]])
B = np.array([[1, -1, 1], [-1, 0, 0], [1, 0, 1]])
AB = A.dot(B)
BA = B.dot(A)
ComAB = np.subtract(AB, BA)
ComAB

array([[ 0, -2,  4],
       [ 2,  0,  3],
       [-4, -3,  0]])

In [23]:
X = np.array([[1, 2], [3, 4]])
keta = np.array([[1],[2]])
braa = np.transpose(keta)
brab = np.array([1, 2, 3])
ketb = np.array([[4],[5],[6]])
inner = brab.dot(ketb)
outer = np.outer(ketb,brab)
inner

array([32])

In [29]:
Z = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
Y = np.array([[5, 6, 7], [3, 4, 5], [1, 2, 3]])
Z.dot(Y)

array([[14, 20, 26],
       [32, 44, 56],
       [50, 68, 86]])

In [28]:
Y.dot(Z)

array([[58, 76, 94],
       [40, 52, 64],
       [22, 28, 34]])